#!/bin/bash

log_date() {
    while IFS= read -r line; do
        echo "$(date) $line"
    done
}

# if first run, flash the printHAT
if [ -f "/boot/firstrun" ]; then 
    
    # Enables NTP to update date and time from internet
    timedatectl set-ntp True | log_date >> /var/log/initlog.log 2>&1
    
	# flash
	cd /home/pi/klipper 
	/usr/bin/make flash FLASH_DEVICE=/dev/ttyAMA0 | log_date >> /var/log/initlog.log 2>&1
    
    #clear terminal history
    cat /dev/null > /home/pi/.bash_history && history -c
    
	# shut down 
	/usr/bin/rm -f /boot/firstrun | log_date >> /var/log/initlog.log 2>&1
	shutdown now | log_date >> /var/log/initlog.log 2>&1
fi
