#!/usr/bin/env bash
# Wrecklab
# Adds to /boot configuration files that setup the firstrun and UART usage
# Written by Wrecklab <wrecklab at wrecklab dot com>
# 
########
set -x
set -e

export LC_ALL=C

source /common.sh

# unpack the content of the module
unpack /filesystem/boot /boot
unpack /filesystem/home/pi /home/"${BASE_USER}"  "${BASE_USER}"
unpack /filesystem/root /

# update files in /boot
sed -i 's/console\=serial0\,115200 //' /boot/cmdline.txt
echo 'enable-uart=1' >> /boot/config.txt
echo 'dtoverlay=pi3-miniuart-bt' >> /boot/config.txt

# enable firstrun daemon 
systemctl_if_exists enable wreck3dctrl.service

# install OctoKlipper plugin
echo "Installing OctoKlipper"
sudo -u "${BASE_USER}" /home/pi/oprint/bin/pip install "https://github.com/thelastWallE/OctoprintKlipperPlugin/archive/master.zip"
