#!/usr/bin/env bash
# Wrecklab
# Adds to /boot configuration files that setup the firstrun and UART usage
# Written by Wrecklab <wrecklab at wrecklab dot com>
# 
########
set -x
set -e

export LC_ALL=C

source /common.sh

# unpack the content of the module
unpack /filesystem/boot /boot
unpack /filesystem/home/pi /home/"${BASE_USER}"  "${BASE_USER}"
unpack /filesystem/root /


# files in boot
sed -i 's/console\=serial0\,115200 //' /boot/cmdline.txt
echo 'enable-uart=1' >> /boot/config.txt
echo 'dtoverlay=pi3-miniuart-bt' >> /boot/config.txt

# files in home
if [ "$WRECKLAB_PRINTHAT_VER" == "v1" ]
then
	echo "--- Configuring printHAT v1"
	cd /home/pi/klipper
	cp phatv1_defconfig .config
    make
    cd ..
    cp klipper/config/generic-wrecklab-printhat-v1-cartesian.cfg printer.cfg
elif [ "$WRECKLAB_PRINTHAT_VER" == "v2" ] 
then
	echo "--- Configuring printHAT v2"
	cd /home/pi/klipper
	cp phatv2_defconfig .config
    make
    cd ..
    cp klipper/config/generic-wrecklab-printhat-v2-cartesian.cfg printer.cfg
fi

# install OctoKlipper plugin
sudo -u "${BASE_USER}" /home/pi/oprint/bin/pip install "https://github.com/thelastWallE/OctoprintKlipperPlugin/archive/master.zip"
