#!/usr/bin/env bash
# Klipper install script
# Script that installs Klipper
########

# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/${BASE_USER} ${BASE_USER}

echo "Installing Klipper"
echo "$KLIPPER_VAR"

apt update
apt install wget git gpiod -y

#Make sure user pi has access to serial ports
usermod -a -G tty pi
usermod -a -G dialout pi

cd /home/pi
sudo -u "${BASE_USER}" git clone $KLIPPER_REPO_SHIP klipper
#cd /home/pi/klipper
#sudo -u "${BASE_USER}" git checkout tags/$KLIPPER_REPO_TAG

sudo -u pi bash /home/pi/install-custompios.sh
sudo -u pi bash /home/pi/install-config.sh $KLIPPER_PHAT_VERSION

rm /home/pi/install-custompios.sh
rm /home/pi/install-config.sh

# Run installation steps defined above
