name: Test tags

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        frontend: [octoprint, mainsail]

    steps:
      # checkout Klipper and set environment
      #- uses: actions/checkout@v2
      #  with:
      #    repository: 'KevinOConnor/klipper'
      #    path: klipper

      #- name: Set Klipper environment
      #  run: |
      #    cd klipper
      #    echo "KLIPPER=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      #    echo ${{ env.KLIPPER }}

      # checkout this repo and  set environment
      - uses: actions/checkout@v2

      - name: Set environment
        run: |
          echo "RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          ls
          echo "KLIPPER=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo ${GITHUB_REF#refs/*/}

      # do some tests
      - name: Test
        env:
          GUI: ${{ matrix.frontend }}
        run: |
          IMAGE=wrecklabOS-$RELEASE-$DATE-$GUI
          BIN=klipper-$KLIPPER-$RELEASE-$DATE
          echo $IMAGE
          echo $BIN
