name: Test tags

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        frontend: [octoprint, mainsail]

    steps:
      - uses: actions/checkout@v2
      - name: Set environment
        run: |
          echo "RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo ${GITHUB_REF#refs/*/}
      - name: Test
        env:
          GUI: ${{ matrix.frontend }}
          NOW: ${date +"%Y%m%d%H%M"}
        run: |
          IMAGE=wrecklabOS-$RELEASE-$NOW-$GUI
          echo $IMAGE
          echo ${{ env.REL }}
